#:kivy 1.11.1
#:import FigureCanvasKivyAgg kivy.garden.matplotlib.backend_kivyagg
#:import plt matplotlib.pyplot

<WellLitPopup>:
	size_hint: None,None
	height: 200
	width: 500

<MetaLabel>:
	text_size: self.size
	halign: 'left'
	padding_x: 5

<PLWidget>:
	orientation: 'vertical'
	BoxLayout:
		orientation: 'horizontal'
		size_hint_y: None
		height: 200
		BoxLayout:
			size_hint_x: .3
			id: metadata_box
			orientation: 'vertical'
			MetaLabel:
				id: user_name_label
				text: 'User Name: \n'
			MetaLabel:
				id: plate_barcode_label
				text: 'Plate Barcode: \n'
			Label:
				size_hint_y: 2
	    Label:
	    	id: notificationLabel
	        text: 'Please scan your name tag'
	        font_size: 20
	        bold: True
    	BoxLayout:
    		size_hint_x: None
    		width: 180
		    orientation: 'vertical'
		    id: button_box
		    TextInput:
		    	id: textbox
		    	multiline: False
		    	size_hint_y: .5
		    	focus: True
		    Button:
		    	text: 'Undo Last Tube'
		    	on_press: root.undoTube()
		    Button:
		    	text: 'Finish Plate'
		    	on_press: root.finishPlate()
		    Button:
		    	text: 'Abort Plate'
		    	on_press: root.abortPlate()
	WellPlot:
		id: wellPlot

		