#:kivy 1.11.1
#:import FigureCanvasKivyAgg kivy.garden.matplotlib.backend_kivyagg
#:import plt matplotlib.pyplot

<MetaLabel>:
	text_size: self.size
	halign: 'left'
	padding_x: 5

<PLWidget>:
	orientation: 'vertical'
	BoxLayout:
		orientation: 'horizontal'
		size_hint_y: None
		height: 180
		BoxLayout:
			size_hint_x: .3
			id: metadata_box
			orientation: 'vertical'
			MetaLabel:
				id: user_name_label
				text: 'User Name: \n'
			MetaLabel:
				id: plate_barcode_label
				text: 'Plate Barcode: \n'
			Label:
				size_hint_y: 2
	    Label:
	    	id: notificationLabel
	        text: 'Please scan your name tag'
	        font_size: 20
	        bold: True
    	BoxLayout:
    		size_hint_x: None
    		width: 180
		    orientation: 'vertical'
		    TextInput:
		    	id: textbox
		    	multiline: False
		    	focus: True
		    Button:
		    	text: 'undo last tube'
		    Button:
		    	text: 'new plate'
		    Button:
		    	text: 'abort'
	WellPlot:
		id: wellPlot

		